### ISSUE TITLE
Single Image Transitioning vs Multiple Image Transitioning

### ISSUE THREAD

**Issue by ps-raghotham-rao** [clovaai/stargan-v2#131]
Not an issue. But just a question.

This might be a beginner level question. I will give a scenario. Like say we have cat, dog and tiger image. And say we are transitioning from cat to dog.

Will the quality of cat to dog transition will be better if we only train with cat and dog images (like cyclegan)?

Or we train with all cat,dog and tiger images?

Like cat as source image. Dog and Tiger as Target Images. Transitioning from cat to dog. And cat to tiger.

Will the quality and accuracy be same when we do multiple transitioning and single transitioning?

**Comment by eps696** [comment]
[disclaimer: i'm not a repo author, but an avid user and huge fan of stargan2 network - here is my [practical remux](https://github.com/eps696/stargan2) btw]. 
on my practice, multiple domains do not spoil the quality [i suspect it may even enhance it, since the shared layers of the netwok obtain more visual knowledge in general]. i used up to 10-12 domains in one model, and got quite satisfying results, visually comparable with sample model from this repo [i haven't run any metrics though].

**Comment by ps-raghotham-rao** [comment]
> [disclaimer: i'm not a repo author, but an avid user and huge fan of stargan2 network - here is my [practical remux](https://github.com/eps696/stargan2) btw]. on my practice, multiple domains do not spoil the quality [i suspect it may even enhance it, since the shared layers of the netwok obtain more visual knowledge in general]. i used up to 10-12 domains in one model, and got quite satisfying results, visually comparable with sample model from this repo [i haven't run any metrics though].

Even while I was testing I found similar results. Thank You!
